esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"
  build_path: "./build/${device_name}"

logger:

binary_sensor:
  - platform: status
    name: "Status"
    entity_category: diagnostic

button:
  - platform: restart
    name: "Restart"
    entity_category: config
  - platform: safe_mode
    name: "Safe Mode"
    entity_category: config
  - platform: shutdown
    name: "Shutdown"
    entity_category: config

sensor:
  - platform: uptime
    name: "Uptime"
    entity_category: diagnostic
  - platform: wifi_signal
    name: "Signal"
    entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
      icon: mdi:ip-network
  - platform: version
    icon: mdi:package-variant
    name: "Version"
    entity_category: diagnostic
