- platform: group
  name: 'Family phones'
  services:
    - service: notify.mobile_app_iphone
    - service: notify.mobile_app_lottes_iphone

- platform: group
  name: 'Family devices'
  services:
    - service: notify.mobile_app_iphone
    - service: notify.mobile_app_lottes_iphone
    - service: notify.mobile_app_macbook_pro_thibault_itp
    - service: notify.mobile_app_lottes_imac

- platform: group
  name: 'Thibault devices'
  services:
    - service: notify.mobile_app_iphone
    - service: notify.mobile_app_macbook_pro_thibault_itp
    - service: notify.mobile_app_thibaults_ipad
