- platform: group
  name: 'Family phones'
  services:
    - service: mobile_app_thibaults_iphone
    - service: mobile_app_lottes_iphone

- platform: group
  name: 'Family devices'
  services:
    - service: mobile_app_thibaults_iphone
    - service: mobile_app_lottes_iphone
    - service: mobile_app_macbook_pro_thibault_itp
    - service: mobile_app_lottes_imac

- platform: group
  name: 'Thibault devices'
  services:
    - service: mobile_app_thibaults_iphone
    - service: mobile_app_macbook_pro_thibault_itp
    - service: mobile_app_thibaults_ipad

- platform: group
  name: 'Lotte devices'
  services:
    - service: mobile_app_lottes_iphone
    - service: mobile_app_lottes_imac
