# Loads default set of integrations. Do not remove.
default_config:

frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  db_url: !secret maria_db_url

ios:
  actions: !include integrations/ios/actions.yaml

alarm_control_panel: !include_dir_merge_list integrations/alarm_control_panel/
sensor: !include_dir_merge_list integrations/sensor

mqtt:
  binary_sensor: !include_dir_merge_list integrations/mqtt/binary_sensor

# HACS
afvalbeheer: !include integrations/hacs/afvalbeheer.yaml
