default_config:

frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  db_url: !secret maria_db_url

# Integrations
cover: !include_dir_merge_list integrations/cover
ios:
  actions: !include integrations/ios/actions.yaml
mqtt:
  binary_sensor: !include integrations/mqtt/binary_sensor.yaml
notify: !include_dir_merge_list integrations/notify
prometheus: !include integrations/prometheus/prometheus.yaml
proximity: !include_dir_merge_named integrations/proximity
rest_command: !include_dir_merge_named integrations/rest_command
sensor: !include_dir_merge_list integrations/sensor
template:
  - binary_sensor: !include_dir_merge_list integrations/template/binary_sensor
  - trigger:
      - platform: time_pattern
        minutes: '/15'
    sensor: !include integrations/template/trigger/sensor.yaml

# Integrations (HACS)
afvalbeheer: !include integrations/hacs/afvalbeheer.yaml
