# Loads default set of integrations. Do not remove.
default_config:

frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  db_url: !secret maria_db_url

prometheus: !include integrations/prometheus/prometheus.yaml

ios:
  actions: !include integrations/ios/actions.yaml

sensor: !include_dir_merge_list integrations/sensor

mqtt:
  binary_sensor: !include integrations/mqtt/binary_sensor.yaml

template:
  - binary_sensor: !include_dir_merge_list integrations/template/binary_sensor
  - sensor: !include_dir_merge_list integrations/template/sensor

notify: !include_dir_merge_list integrations/notify

# HACS
afvalbeheer: !include integrations/hacs/afvalbeheer.yaml
