# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  db_url: !secret maria_db_url

alarm_control_panel: !include_dir_merge_list integrations/alarm_control_panel/

ios:
  actions: !include integrations/ios/actions.yaml

# HACS
afvalbeheer: !include integrations/hacs/afvalbeheer.yaml
