- platform: template
  covers:
    garage_door:
      device_class: garage
      unique_id: garage_door
      friendly_name: 'Garage door'
      value_template: >-
        {% if is_state('binary_sensor.contactsensor_garagepoort_contact', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >-
        {% if is_state('binary_sensor.contactsensor_garagepoort_contact', 'on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garagepoort
      close_cover:
        service: switch.turn_on
        data:
          entity_id: garagepoort
      stop_cover:
        service: switch.turn_on
        data:
          entity_id: garagepoort
