substitutions:
  device_name: 'esp32-ledstrip-tv-kamer-links'
  friendly_name: 'LED Strip TV Kamer (Links)'

esp32:
  board: esp32dev

packages:
  base_config: !include ./shared/base_config.yaml
  wifi: !include ./shared/wifi.yaml
  api: !include ./shared/api.yaml
  metrics: !include ./shared/metrics.yaml

output:
  - platform: ledc
    pin: GPIO33
    id: pwm_channel

light:
  - platform: monochromatic
    id: ledstrip
    name: "Light"
    output: pwm_channel

binary_sensor:
  - platform: gpio
    name: "Power"
    internal: true
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - light.toggle:
          id: ledstrip
    on_click:
      min_length: 2s
      max_length: 3s
      then:
        - light.turn_on:
            id: ledstrip
            brightness: 100%
