substitutions:
  device_name: 'esp8266-desk-controller'
  friendly_name: 'Desk Controller (Bureau Thib)'

esp8266:
  board: nodemcuv2

packages:
  base_config: !include ./shared/base_config.yaml
  wifi: !include ./shared/wifi.yaml
  api: !include ./shared/api.yaml
  metrics: !include ./shared/metrics.yaml
  mqtt: !include ./shared/mqtt.yaml

binary_sensor:
#   GPIO Pin 16 does not support pullup pin mode. Please choose another pin.
  # - platform: gpio
  #   name: "Button 1"
  #   internal: true
  #   pin:
  #     number: D0
  #     mode: INPUT_PULLUP
  #     inverted: true
  #   on_press:
  #     - mqtt.publish:
  #         topic: "esphome/${device_name}/button"
  #         payload: "1"
  #   on_click:
  #     min_length: 1s
  #     max_length: 2s
  #     then:
  #       - mqtt.publish:
  #           topic: "esphome/${device_name}/button_hold"
  #           payload: "1"

  - platform: gpio
    name: "Button 2"
    internal: true
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "1"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "1"

  - platform: gpio
    name: "Button 3"
    internal: true
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "1"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "1"
