substitutions:
  device_name: 'esp8266-roomnode-gang-beneden'
  friendly_name: 'Roomnode Gang (Beneden)'
  room: 'Gang (Beneden)'

esp8266:
  board: d1_mini

packages:
  base_config: !include ./shared/base_config.yaml
  wifi: !include ./shared/wifi.yaml
  api: !include ./shared/api.yaml
  metrics: !include ./shared/metrics.yaml
  i2c: !include ./shared/i2c.yaml

  roomnode: !include ./lib/roomnode.yaml

sensor:
  - platform: bh1750
    address: 0x23
    name: "${room} Illuminance"
