substitutions:
  device_name: 'esp8266-roomnode-bureau-thib'
  friendly_name: 'Roomnode Bureau Thib'
  room: 'Bureau Thib'

esp8266:
  board: d1_mini

packages:
  base_config: !include ./shared/base_config.yaml
  wifi: !include ./shared/wifi.yaml
  api: !include ./shared/api.yaml
  metrics: !include ./shared/metrics.yaml
  i2c: !include ./shared/i2c.yaml

  roomnode: !include ./lib/roomnode.yaml
