substitutions:
  device_name: sonoff-rf-bridge
  friendly_name: "Sonoff RF Bridge"

esp8266:
  board: esp8285

logger:
  baud_rate: 0

packages:
  base_config: !include ./shared/base_config.yaml
  wifi: !include ./shared/wifi.yaml
  api: !include ./shared/api.yaml
  mqtt: !include ./shared/mqtt.yaml

uart:
  tx_pin: GPIO01
  rx_pin: GPIO03
  baud_rate: 19200

api:
  services:
    - service: send_code
      variables:
        sync: int
        low: int
        high: int
        code: int
      then:
        - rf_bridge.send_code:
            sync: !lambda 'return sync;'
            low: !lambda 'return low;'
            high: !lambda 'return high;'
            code: !lambda 'return code;'
    - service: learn
      then:
        - rf_bridge.learn

rf_bridge:
  on_code_received:
    then:
      - light.toggle: wifi_led
      - light.toggle: wifi_led
      - homeassistant.event:
          event: esphome.rf_code_received
          data:
            sync: !lambda 'char buffer [10];return itoa(data.sync,buffer,16);'
            low: !lambda 'char buffer [10];return itoa(data.low,buffer,16);'
            high: !lambda 'char buffer [10];return itoa(data.high,buffer,16);'
            code: !lambda 'char buffer [10];return itoa(data.code,buffer,16);'
      - mqtt.publish:
          topic: '${device_name}/rf/received'
          payload: !lambda |-
            char sync_buff [10];
            char low_buff [10];
            char high_buff [10];
            char code_buff [10];

            std::string sync = itoa(data.sync, sync_buff, 16);
            std::string low = itoa(data.low, low_buff, 16);
            std::string high = itoa(data.high, high_buff, 16);
            std::string code = itoa(data.code, code_buff, 16);

            return "sync=" + sync + ",low=" + low + ",high=" + high + ",code=" + code;

binary_sensor:
  - platform: status
    name: "Status"
    on_state:
      then:
        - light.turn_on: wifi_led
  - platform: gpio
    name: "Pair Button"
    pin: GPIO00

light:
  - platform: binary
    id: wifi_led
    name: "Wifi LED"
    internal: True
    output: output_wifi_led

output:
  - platform: gpio
    id: output_wifi_led
    pin:
      number: GPIO13
      inverted: True
